# Use official Java image
FROM eclipse-temurin:17-jdk-alpine

# Set working directory
WORKDIR /app

# Copy entire project into /app
COPY . .

# Make mvnw executable (if you're using mvnw)
RUN chmod +x mvnw

# Build the project
RUN ./mvnw clean install -DskipTests

# Expose default Spring Boot port
EXPOSE 8080

# Start the app
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]
